--- # Playbook for installing and configuring Wordpress
- hosts: dev
  user: ec2-user
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Apache
      yum: name=httpd state=latest
    - name: Install additional packages
      yum: name={{ item }} state=latest
      with_items:
      - php
      - php-mysql
    - name: Download wordpress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress-latest.tar.gz force=yes
    - name: Extract wordpress
      shell: "tar xzf /var/www/html/wordpress-latest.tar.gz -C /var/www/html --strip-components 1"
    - name: Make my Document Root readable
      file:
        path: /var/www/html
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: apache
        group: apache
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      service: name=httpd enabled=yes state=restarted
...

