variable "aws_region" {}
variable "aws_profile" {}
variable "keypath" {}
variable "instance_key_name" {}
variable "instance_key_path" {}
variable "ansible_key_name" {}
variable "ansible_key_path" {}
variable "authorized_keys" {}
variable "private_key" {}
variable "instance_type" {}
variable "ami" {}
variable "elb_healthy_threshold" {}
variable "elb_unhealthy_threshold" {}
variable "elb_timeout" {}
variable "elb_interval" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_grace" {}
variable "asg_hct" {}
variable "asg_cap" {}
variable "instance_count" {}