variable "aws_region" {}
variable "aws_profile" {}
variable "localip" {}
variable "key_name" {}
variable "public_key_path" {}
variable "domain_name" {}
variable "instance_type" {}
variable "ami" {}
variable "elb_healthy_threshold" {}
variable "elb_unhealthy_threshold" {}
variable "elb_timeout" {}
variable "elb_interval" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_grace" {}
variable "asg_hct" {}
variable "asg_cap" {}
variable "master_count" {}
variable "slave_count" {}